// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzwHgqeaadRoeQKk3WPGX3msxE90d9p5w',
    appId: '1:56237864895:web:3bb4988ae423d2912b530a',
    messagingSenderId: '56237864895',
    projectId: 'mynote-1d4f5',
    authDomain: 'mynote-1d4f5.firebaseapp.com',
    storageBucket: 'mynote-1d4f5.appspot.com',
    measurementId: 'G-7BHSK767MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl_Tb8gwL0wdLO_JPOdI_Ni5W99Dj3h-k',
    appId: '1:56237864895:android:9230ca5f31477a172b530a',
    messagingSenderId: '56237864895',
    projectId: 'mynote-1d4f5',
    storageBucket: 'mynote-1d4f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV365DzNSWbVePze2aq2zrtQB2dtjU-aM',
    appId: '1:56237864895:ios:8da697cd35895f432b530a',
    messagingSenderId: '56237864895',
    projectId: 'mynote-1d4f5',
    storageBucket: 'mynote-1d4f5.appspot.com',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV365DzNSWbVePze2aq2zrtQB2dtjU-aM',
    appId: '1:56237864895:ios:5986b55ed1294f8d2b530a',
    messagingSenderId: '56237864895',
    projectId: 'mynote-1d4f5',
    storageBucket: 'mynote-1d4f5.appspot.com',
    iosBundleId: 'com.example.flutterTask.RunnerTests',
  );
}
